export { device } from './device/index.js'
export { setDevice } from './device/index.js'
export { AndroidDevice } from './device/android-device.js'
export { IOSDevice } from './device/ios-device.js'
export { element } from './element/element.js'
export { by } from './element/by.js'
export { defineConfig } from './config.js'
export { mobileTestPlugin } from './vitest/plugin.js'

export type { Device, DeviceInfo, LaunchOptions, OpenUrlOptions, WaitForAnimationOptions } from './device/types.js'
export type { IOSAppConfig, MobileTestConfig, ResolvedConfig } from './config.js'
export type { Locator } from './element/by.js'
export type { Element } from './element/element.js'
export type { ElementHandle, Frame } from './element/types.js'
export type { CompareOptions, ComparisonResult } from './screenshot/compare.js'
export { takeAndCompare, type TakeAndCompareOptions, type ScreenshotResult } from './screenshot/workflow.js'
export { normalizeStatusBar, resetStatusBar } from './screenshot/normalize.js'
export { DriverClient } from './driver/client.js'
export { launchDriver } from './driver/installer.js'
export { setDriverClient } from './driver/context.js'
export { setTestConfig } from './config-context.js'
export { log, setLogLevel } from './logger.js'
export type { LogLevel } from './logger.js'
export type { DriverProcess } from './driver/installer.js'
